# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 17) do

  create_table "articles", :force => true do |t|
    t.column "user_id",          :integer
    t.column "title",            :string
    t.column "content",          :text
    t.column "extended_content", :text
    t.column "created_at",       :datetime
    t.column "is_active",        :boolean
  end

  add_index "articles", ["is_active", "created_at"], :name => "postable_content"
  add_index "articles", ["created_at"], :name => "created_at_ndx"
  add_index "articles", ["user_id", "created_at"], :name => "user_ndx"

  create_table "comments", :force => true do |t|
    t.column "title",            :string,   :limit => 50, :default => ""
    t.column "comment",          :text
    t.column "created_at",       :datetime,                               :null => false
    t.column "commentable_id",   :integer,                :default => 0,  :null => false
    t.column "commentable_type", :string,   :limit => 15, :default => "", :null => false
    t.column "user_id",          :integer,                :default => 0,  :null => false
  end

  add_index "comments", ["user_id"], :name => "fk_comments_user"

  create_table "invitations", :force => true do |t|
    t.column "email",           :string
    t.column "activation_code", :string,   :limit => 40
    t.column "created_at",      :datetime
    t.column "invitation_id",   :integer
    t.column "about_me",        :text
  end

  create_table "pages", :force => true do |t|
    t.column "content", :text
    t.column "name",    :string
  end

  add_index "pages", ["name"], :name => "name_ndx"

  create_table "podcasts", :force => true do |t|
    t.column "title",        :string
    t.column "description",  :text
    t.column "size",         :integer
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "created_at",   :datetime
    t.column "is_active",    :boolean
    t.column "user_id",      :integer
  end

  add_index "podcasts", ["is_active", "created_at"], :name => "active_date_ndx"
  add_index "podcasts", ["user_id", "created_at"], :name => "user_ndx"
  add_index "podcasts", ["created_at"], :name => "created_ndx"

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "talks", :force => true do |t|
    t.column "user_id",          :integer
    t.column "title",            :string
    t.column "content",          :text
    t.column "extended_content", :text
    t.column "created_at",       :datetime
    t.column "is_active",        :boolean
    t.column "priority",         :integer,  :default => 0
    t.column "last_commented",   :datetime
  end

  add_index "talks", ["is_active", "created_at"], :name => "postable_content"
  add_index "talks", ["created_at"], :name => "created_at_ndx"
  add_index "talks", ["user_id", "created_at"], :name => "user_ndx"

  create_table "user_subscribes", :force => true do |t|
    t.column "subscribtable_id",   :integer,                :default => 0,  :null => false
    t.column "subscribtable_type", :string,   :limit => 15, :default => "", :null => false
    t.column "user_id",            :integer,                :default => 0,  :null => false
    t.column "created_at",         :datetime,                               :null => false
    t.column "updated_at",         :datetime,                               :null => false
  end

  add_index "user_subscribes", ["user_id"], :name => "fk_subscribes_user"

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "activation_code",           :string,   :limit => 40
    t.column "activated_at",              :datetime
    t.column "admin",                     :boolean,                :default => false
    t.column "icon",                      :string
    t.column "invitations",               :integer,                :default => 2
    t.column "invitation_id",             :integer,                :default => 0
  end

end
